version: "2"
services:
  web:
    build: ./api
    ports:
      - "3000:3000"
    command: npm run start
    volumes:
      - ./api/src:/usr/src/app/src/
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
